export const carData = [
  { value: "buick", label: "Buick" },
  { value: "volvo", label: "Volvo" },
  { value: "hummer", label: "HUMMER" },
  { value: "subaru", label: "Subaru" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "nissan", label: "Nissan" },
  { value: "lincoln", label: "Lincoln" },
  { value: "gmc", label: "GMC" },
  { value: "hyundai", label: "Hyundai" },
  { value: "mini", label: "MINI" },
  { value: "bentley", label: "Bentley" },
  { value: "mercedes-benz", label: "Mercedes-Benz" },
  { value: "aston-martin", label: "Aston Martin" },
  { value: "pontiac", label: "Pontiac" },
  { value: "lamborghini", label: "Lamborghini" },
  { value: "audi", label: "Audi" },
  { value: "bmw", label: "BMW" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "chrysler", label: "Chrysler" },
  { value: "kia", label: "Kia" },
  { value: "land", label: "Land" },
  { value: "lexus", label: "Lexus" },
  { value: "tesla", label: "Tesla" },
  { value: "porsche", label: "Porsche" },
  { value: "jaguar", label: "Jaguar" },
  { value: "acura", label: "Acura" },
  { value: "infiniti", label: "Infiniti" },
];

export const priceData = [
  { value: "30", label: "30" },
  { value: "40", label: "40" },
  { value: "50", label: "50" },
  { value: "60", label: "60" },
  { value: "70", label: "70" },
  { value: "80", label: "80" },
  { value: "90", label: "90" },
  { value: "100", label: "100" },
  { value: "110", label: "110" },
  { value: "120", label: "120" },
  { value: "130", label: "130" },
  { value: "140", label: "140" },
];
